
version: 2.1

workflows:
  all:
    jobs:
      - build
      - lint
      - test
      - plan
      - deploy:
        filters:
          branches:
            only:
              - master

executors:
  default-executor:
    docker:
       # this image is built from https://github.com/lynncyrin/docker-images
       - image: lynncyrin/go-web-server:1585813995

jobs:

  build:
    executor: default-executor
    steps:
      - checkout
      - run: ./scripts/build.sh

  lint:
    executor: default-executor
    steps:
      - checkout
      - run: ./scripts/lint.sh

  test:
    executor: default-executor
    steps:
      - checkout
      - run: ./scripts/test.sh

  plan:
    executor: default-executor
    steps:
      - checkout
      - run: ./scripts/plan.sh

  deploy:
    executor: default-executor
    steps:
      - checkout
      - run: ./scripts/deploy.sh
