
version: 2.1

workflows:
  all:
    jobs:
      - build
      - lint
      - test

executors:
  default-executor:
    docker:
       - image: lynncyrin/go-web-server:1584428789

jobs:

  build:
    executor: default-executor
    steps:
      - checkout
      - run: ./scripts/build.sh

  lint:
    executor: default-executor
    steps:
      - checkout
      - run: ./scripts/lint.sh

  test:
    executor: default-executor
    steps:
      - checkout
      - run: ./scripts/test.sh
